### ISSUE TITLE
Quel est l'objectif mathématique à optimiser ? 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#10]
[From Samuel]Je comprends qu'on veut optimiser le maillage. Ça serait x dans le programme max_{x \in C} f(x). Mais il manque deux choses à définir:
1. L'objectif (décrit par la fonction f): par exemple, j'aurais envie de dire "le nombre de repas servis"... Mais ça pourrait être autre chose, j'ignore à peu près tout de ce qu'ils font à la Croix Rouge!
2. Les contraintes (décrites par l'ensemble C): j'imagine qu'ils sont limités par le temps disponible des bénévoles, et les quantités disponibles de nourriture. Mais peut-être aussi d'autres choses auxquelles je n'ai pas pensé.

**Comment by martindaniel4** [comment]
1 / L objectif ce serait que toute personne qui a faim (les bénéficiaires) doit pouvoir trouver à manger dans un centre de distribution. Est ce que ça correspond à ce que tu imagines ?

2 / Absolument, ils ont plusieurs contraintes :
- Des stocks limités qui leur sont attribués principalement par la banque alimentaire.
- Des volontaires limités et qui tournent souvent
- Des emplacements de centres se distribution.

On peut pas vraiment jouer sur les deux premières variables. C est du flux tendu. En revanche on peut jouer sur la troisième en donnant une autre répartition du maillage (via notamment des deals avec les magasins de la grande distribution)

**Comment by martindaniel4** [comment]
[From Samuel] 1/ OK c'est l'objectif "first best" disons (on en est loin d'ailleurs?). Quels seraient d'autres objectifs ("second best") envisageables dans le cas où le "first best" n'est pas possible?

2/ Je vois! Du coup, il doit y avoir des maillages acceptables et non-acceptables selon les contraintes de disponibilité des volontaires (je fais l'hypothèse que les stocks doivent être déplacés entre les points de distribution de la banque alimentaire et les points du maillage de la CR, et qu'il faut des volontaires conduisant des voitures / camions pour cela). Quelles données a-t-on sur ces contraintes? Par ailleurs, a-t-on une liste de tous les endroits potentiels où la CR pourrait ouvrir ses centres?

**Comment by martindaniel4** [comment]
@samronsin : 

1/ On ne sait pas du tout justement si le maillage est optimal justement. Je pense que la première étape est justement de prédire la demande et de confronter ça au mapping des centres existants. 

2/ On a pour l'instant pas de données sur ces contraintes. Comme je le te disais, et étant donné que c'est du flux tendu, il n'y a pas vraiment de leviers sur les stocks ou les volontaires. Si on a toutefois une demande précise, on peut revenir vers la CRF. On a créé une issues ici avec les données supplémentaires qui seraient nécessaires (https://github.com/dataforgoodfr/croixrouge/issues/1), hésite pas à le compléter !

**Comment by c-o** [comment]
@samronsin : 
Merci de nous prêter main forte!
1/
La Croix Rouge est très évasif sur son objectif, leur problème c’est
“nos centres se sont ouverts de manières indépendantes, et on ne sait pas s’il y en a trop dans certaines régions (on s’en doute: il y a des centres avec 3 repas distribués par mois), ni si des régions en manquent."
L’identification des zones surinvesties leur permettrait d’économiser des efforts peu rentables socialement,
et celles sous investies, d’insister, chiffres à l’appui auprès des élus et entrepos locaux sur la nécessité d’implanter un centre / accroitre les efforts.
En pratique ils ne vont donc pas chambouler tout le maillage, même si ce serait utile d’avoir un maillage théorique optimal pour savoir vers quoi on pourrait tendre si on n'avait pas de contraintes. 

J’imagine qu’un maillage optimal doit répondre à un critère du type
90% des gens en dessous du seuil de pauvreté-en-besoin-alimentaire 0.8 sont couverts par un centre de distribution à moins de 40 km
du coup on peut chercher avoir plusieurs solutions en privilégiant 1 des 3 critères à la fois (en fixant les autres)
a priori il faudra commencer par définir ce que signifie “seuil de pauvreté-en-besoin-alimentaire”, c’est une fonction qui intéresse bcp la croix rouge: comment, à partir de données ouvertes existantes déterminer le nombre de personnes dans le besoin.

2/
 re:>  il doit y avoir des maillages acceptables et non-acceptables 
Les contraintes les plus fortes seront en effet la mobilité des volontaires, mais aussi la possibilité d’avoir des locaux ainsi que leur taille… ou encore la présence d’une autre association à proximité!
 re:> Quelles données a-t-on sur ces contraintes
pas moyen d’avoir des données là dessus. On va donc devoir travailler sur des maillages “théoriques”
 re:> Par ailleurs, a-t-on une liste de tous les endroits potentiels où la CR pourrait ouvrir ses centres?
on pourrait en effet leur demander s’il y a des zones particulières où ils sont en discussions / négociation, histoire de faire des focus sur ces zones et leur donner des bons chiffres. Mais plus généralement, il était plus questions que ce soit nous qui leur proposions des zones, à eux après de piocher dedans.

**Comment by martindaniel4** [comment]
@c-o agreed !

**Comment by samronsin** [comment]
@martindaniel4 @c-o merci pour vos réponses!

1/ @martindaniel4 Oui bien sûr, j'ai dû mal m'exprimer -- il s'agit de se mettre d'accord sur les métriques à optimiser via les maillages. Je déduis de ta réponse qu'on ne sait pas évaluer le maillage actuel (dis-moi si je me trompe). Le benchmarking par rapport à la demande (qu'il s'agirait de déterminer) que tu proposes viserait à minimiser le nombre de repas demandés et non-servis. Cela revient in fine à maximiser le nombre de repas servis, qui semble donc être une bonne base pour la métrique à maximiser du point de vue des bénéficiaires (à discuter avec la CRF?). Quid du transport des bénéficiaires? Il faudrait le prendre en compte dans la métrique (par ex. probabilité de pouvoir se rendre à un centre = fonction décroissante (à fitter) du temps de trajet domicile / centre).
@c-o Si je comprends bien les enjeux (politiques): il ne s'agit donc pas tant de proposer des solutions que des arguments à la CRF pour ouvrir / fermer des centres. On pourrait donc envisager plusieurs objectifs (métriques) qui correspondraient à différents points de vue (bénéficiaires, volontaires, ...).

2/ @martindaniel4 On peut envisager demander à la CRF la localisation / disponibilité des volontaires (ou des agrégats)? @c-o OK il va falloir faire beaucoup d'hypothèses! Dans un premier temps, on peut se dire que des centres pourraient être implantés dans chaque commune...

**Comment by martindaniel4** [comment]
@samronsin : 

1/
 `Cela revient in fine à maximiser le nombre de repas servis` exactement ! 
`probabilité de pouvoir se rendre à un centre = fonction décroissante` putain pas mal, j'y avais pas pensé ! Faudrait en parler à la Croix Rouge, à mon sens il n'y a de toute façon pas assez de volontaires. En revanche si tu arrives à dire : voilà l'endroit où il faudrait en trouver et qu'on priorise des campagnes de sensibilisation, ça fait sens. 

2/ - Je ne sais pas si on peut avoir la donnée de localité des volontaires. Je l'ai ajouté à la liste des [datasets à chopper](https://github.com/dataforgoodfr/croixrouge/issues/1). @c-o : Angélique t'avait parlé de ça aux Webassos non ?
