### ISSUE TITLE
Préparer présentation meetup 12 mai 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#14]
- Présenter le contexte et l'enjeu
- Présenter les données

**Comment by martindaniel4** [comment]
@c-o @samronsin intéressant de comparer l'implantation restos du coeur / croix rouge, notamment dans le nord : 

(vert : restos du coeur / orange : crf) 

![capture d ecran 2015-05-11 a 14 04 01](https://cloud.githubusercontent.com/assets/695006/7564493/80465ef6-f7e7-11e4-8dea-dfd7f885c9c1.png)

@c-o comment t'as fait pour lier les données des quartiers prioritaires au coordonnées géographiques ?

**Comment by samronsin** [comment]
@martindaniel4 cool!

**Comment by c-o** [comment]
@martindaniel4 j'ai utilisé l'api google maps

**Comment by martindaniel4** [comment]
@c-o @samronsin ok, mais en gros quel département / localité on cible ? 

@c-o c'est quoi du coup les départements où la distance moyenne entre les centres et les quartiers prioritaires sont les plus importants ? 

@samronsin dans quel département, le nombre de centres (Croix Rouge, Restos du coeur etc..) est le moins important vs nombre de chômeurs ou revenus très faible ?

**Comment by c-o** [comment]
du côté de valencienne m'avait l'air intéressant, mais je regards pour lier ça avec les surplus
je viens aussi de regarder un peu les "déserts" CRF? c'est des petits bleds, et il y a restau du coeur
je m'y remets après 21H ce soir,
j'essaye encore de faire le lien triplet, au pire je trouve des stats / visu sur les pbs de densité, et on fera un slide à part sur les surplus
top si on a aussi qqs visu avec les infos sur le chomage (dans les zones "semi désertiques")
à tout'
