### ISSUE TITLE
Data - intégration des données brutes ? 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#15]
CRF va nous mettre à disposition les données brutes anonymisées de la base AIDA des donations aux bénéficiaires (100Go) à priori sous la forme d'un CSV. 

Je pensais stocker ça sur BigQuery - https://bigquery.cloud.google.com/ qui a l'avantage d'avoir : 
- Interface SQL hyper simple pour travailler 
- Intégration facile avec pandas - http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.gbq.read_gbq.html
- Possibilité de gérer les accès des DS volontaires

Faudra juste que je mette une CB. 

@RomainWarlop @c-o @samronsin @NebJ @lefko2000 @rquilliet - ça vous va ou vous avez d'autres idées ?

**Comment by c-o** [comment]
:+1:

**Comment by martindaniel4** [comment]
Done le 24.04
