### ISSUE TITLE
Prédire les parts restantes pour le mois prochain par centre

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#17]

**Comment by c-o** [comment]
vous avez vu des stocks finalement dans les data et pas du flux tendu comme le disait la croix rouge? ils ont bien insisté là dessus qd mm (tout part en qqs jours, pas de reste plus d'1 semaine quand l'approvisionnement s'arrête)

**Comment by martindaniel4** [comment]
@c-o bah faut analyser les données ;)

**Comment by c-o** [comment]
ok. pour une analyse on pourra déterminer des produits et zones particuliers où il y a en effet du stock, mais pour un modèle prédictif, ça sera trop bruité / biaisé : on risque de ne voir que des artefacts.
Une possibilité: faire un focus sur les épiciries solidaires (20% des centres), Ils ont sans doute plus un format apte au "stockage".
ils pourraient d'ailleurs être plus facilement intéressées par des mises en relation avec grande distrib puisqu'ils travaillent sur le même mode (et non en "colis" donnés).

**Comment by martindaniel4** [comment]
@c-o yes bonne idée. Tu prends le lead là dessus ?

**Comment by martindaniel4** [comment]
@RomainWarlop t'as essayé de faire ça ?

**Comment by martindaniel4** [comment]
@RomainWarlop t'as pu avancé du coup ?

**Comment by RomainWarlop** [comment]
@martindaniel4 yes j'ai essayé quelques trucs :
- une série temporelle par centre, mais y'avait beaucoup trop de données manquantes, le modèle n'a rien donné
- un elastic net et le modèle "factorization matrix" pour que le modèle apprenne de tout les centres en même temps en prenant comme variable id centre, sur famille, année, mois. Et pour l'instant le modèle ne marche pas du tout ... 
  Soit comme le disait @c-o ou me disait @lefko2000, c'est beaucoup trop bruité comme donnée. Donc soit je vais me concentré sur une partie des données soit rajouter des variables contextuelles (géoloc, INSEE, ...)

**Comment by martindaniel4** [comment]
@RomainWarlop ok pour l'instant on regarde des stocks. Donc y aura pas beaucoup de variations. 

Je pense que ça commencera à être cool quand on aura les données par bénéficiaires. Y aura plus de variations.

**Comment by RomainWarlop** [comment]
@martindaniel4 yes je suis d'accord. J'ai hâte d'avoir ces données ;)

**Comment by martindaniel4** [comment]
:+1:  Soon !

**Comment by martindaniel4** [comment]
duplicate https://github.com/dataforgoodfr/croixrouge/issues/37
