### ISSUE TITLE
Lier les données INSEE aux données par centre CRF

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#18]

**Comment by martindaniel4** [comment]
@samronsin t'as réussi à faire un premier essai ?

**Comment by martindaniel4** [comment]
Yo @samronsin ! t'as réussi à sortir quelque chose avec les données INSEE ?

**Comment by samronsin** [comment]
I'm on it!

**Comment by samronsin** [comment]
Il faut attribuer le code géographique INSEE CODGEO à chaque centre, ce qui permettra de récupérer toutes les données de la commune / département (chômage, population). J'ai pas regardé sur BQ, mais comme on ne l'a pas en agrégé, je doute qu'on l'ait en détail. Tu peux confirmer @martindaniel4 ?

**Comment by martindaniel4** [comment]
@samronsin hmm t'as pas de latitude / longitude ? 

Sinon pour transformer INSEE CODGEO, t'as checké ça ? https://github.com/anthill/open-moulinette/tree/master/insee-iris

**Comment by samronsin** [comment]
On a latitude / longitude pour les centres?

**Comment by martindaniel4** [comment]
@samronsin et oui cousin ! https://github.com/dataforgoodfr/croixrouge/blob/master/data/croixrouge/position_centres_2015_CRF.xlsx

**Comment by samronsin** [comment]
Cool, merci!

**Comment by samronsin** [comment]
Avec ça, on devrait y arriver... https://www.data.gouv.fr/fr/datasets/listes-des-communes-geolocalisees-par-regions-departements-circonscriptions-nd/

**Comment by martindaniel4** [comment]
héhé

**Comment by martindaniel4** [comment]
@dataforgoodfr/datagooders j'ai ajouté la liste [des quartiers prioritaires](http://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000030007934&categorieLien=id) définis dans par le Décret n° 2014-1750 du 30 décembre 2014. 

Accessible là - https://github.com/dataforgoodfr/croixrouge/commit/3e238fff97c61e4654cc66be4a4405471b0b6da1

**Comment by martindaniel4** [comment]
ola @samronsin je suis en train de faire la présentation de mardi. 

J'aimerais notamment faire une carte avec plusieurs calques (taux de pauvreté, implantation des Unités de distribution, implantation des autres associations etc..) pour un endroit / quartier prioritaire. Je pense par exemple au 93 ou au Nord. 

Si t'as des choses à m'envoyer hésite pas..

**Comment by martindaniel4** [comment]
J'ai aussi ajouté les codes / lattitude INSEE ici - https://github.com/dataforgoodfr/croixrouge/commit/9a0e486e8015a27c1a2e1ece02e27e4bcdfb8979

**Comment by c-o** [comment]
@martindaniel4 @samronsin pour les quartiers prio, je les ai ajoutés jeudi avec leur coordonnées GPS (j'ai pris le centre des polygones): data/croixrouge/position_quartiers_prioritaires_2015.csv
y'a aussi dans data/ la liste des centres banque alimentaire et restos du coeur.
j'ai tenté de faire des carto avec, mais pas très lisible de manière brute : trop de points (surtout restos du coeur), je vais voir pour un zoom sur qqs departs, sinon faut faire un scoring de densité

**Comment by c-o** [comment]
@martindaniel4 @samronsin j'ai commité un notebook python : commit  0a104dc
dans misc/overlay_... qui montre une carte avec quarties sensibles (cercles larges noirs transparents), CRF (rouge), restos du coeur (bleu), banque alimentaire (vert).
dites moi si ça tourne chez vous (pas le courage de regarder ce soir comment en faire une carte à partager)
j'ai centré sur les alentours de Valencienne, peu de CRF et bizarrement très peu de restos du coeur (à valider le scrapping + voir s'il n'y a pas une assoc locale)
un peu au sud il y a un bled Le Quesnoy avec aucune assoc
Sinon j'ai vu du côté de Lyon, La CRF est très présente... en plein centre, alors que les quartiers prio sont bien plus éloignés en périphérie
le 93, plus difficile de trouver rapidement les points à améliorer: beaucoup de tout, sans doute il manque des points de distribution, mais faudra plus prendre en compte la densité de population
je m'y remets demain soir.

**Comment by samronsin** [comment]
@c-o cool les données quartiers prioritaires! pas pu ouvrir le notebook par contre: erreur "bad request"...

**Comment by samronsin** [comment]
@c-o au temps pour moi, ipython n'était pas à jour chez moi, ça marche maintenant!

**Comment by samronsin** [comment]
preview avec le taux de chômage 
![capture d ecran 2015-05-11 a 17 59 25](https://cloud.githubusercontent.com/assets/2240469/7569431/048e5468-f809-11e4-99cb-a44a16c29792.png)

**Comment by martindaniel4** [comment]
@samronsin très cool. 

Comme on se le disait, on manque de data (vs le simple taux de chômage) pour avoir une bonne variation par commune. 

On pourrait avoir : 
- Le revenu par commune (histoire de calculer le taux de grande pauvreté par commune) 
- Le nombre de chômeurs par commune

**Comment by samronsin** [comment]
yes, voici le nombre de chômeurs par commune (fin 2011), les variations sont beaucoup plus nettes!
en fait ce qu'il faudrait estimer en proirité, c'est le nombre (absolu) de bénéficiaires potentiels à chaque point de la carte. on peut se dire que le nombre de demandeurs d'emploi est une approximation raisonnable (à un facteur près qui correspondrait à celui entre un actif et ceux qui dépendent de lui).

![capture d ecran 2015-05-11 a 18 43 54](https://cloud.githubusercontent.com/assets/2240469/7570156/355f4908-f80e-11e4-8356-5d24314f5748.png)

**Comment by martindaniel4** [comment]
> c'est le nombre (absolu) de bénéficiaires potentiels à chaque point de la carte

@samronsin on pourrait pas faire ça avec les données qu'on a de CRF sur les bénéficiaires ? 

On a une table dans les données brutes, avec une ligne par donation par bénéficiaire..

**Comment by samronsin** [comment]
si on prend des données par centre, et qu'on dit que ça correspond à ce qui se passe dans la commune qui héberge le centre, on fait implicitement l'hypothèse que les bénéficiaires d'un centre sont résidents de la commune qui l'héberge...

**Comment by c-o** [comment]
@lefko2000 a rajouté les volumes stock conso et restants par centres CRF pour tous les centres. Du coup on pourrait rendre variable la taille des rond CRF pour avoir une idée de la conso (en espérant trouver par ex un excédant haut de seine sud vs nord)
de mon côté j'ai fait un maillage de toute la france avec une densité de quartier prio vs centres CRF
a priori les points d'intérêts serait:
manque de CRF:
- Sud de valencienne
- Est de vienne
- Nord de Vienne
  
  trop de CRF:
- Sud de perpignant
- Nord est d'Auxerre

Je vais voir si je peux faire une carte avec ça

**Comment by martindaniel4** [comment]
@c-o mortel ! 

@samronsin tu penses pouvoir intégrer ça dans ta map ? On peut régler la taille des bulles avec le paramètre size de mémoire

**Comment by martindaniel4** [comment]
@dataforgoodfr/datagooders ca donne donc ça. 

Le ratio # centres / chômeurs sont parlants je trouve. On pourrait étendre l'analyse à la France pour voir ce que ça donne : 

![capture d ecran 2015-05-12 a 13 11 47](https://cloud.githubusercontent.com/assets/695006/7586006/aedb77c6-f8a8-11e4-8504-84362720c0cf.png)

**Comment by martindaniel4** [comment]
ok version rectifiée : 

![capture d ecran 2015-05-12 a 15 01 59](https://cloud.githubusercontent.com/assets/695006/7587614/e3ca642e-f8b7-11e4-8ae0-b219ad9ef275.png)

**Comment by samronsin** [comment]
top!

**Comment by martindaniel4** [comment]
@samronsin t'as réussi à intégrer les données de @lefko2000 ? Je serais intéressé de voir ce que donne le volume / centre entre le 92 nord et le sud.

**Comment by samronsin** [comment]
Yes, voici le flux localisé qui a bien l'air plus important au nord du 92 qu'au sud!
Deux mises en garde:
- j'ai regroupé les centres qui étaient localisés au même endroid (même commune)
- j'ai choisi de représenter le poids proportionnellement au _rayon_ des disques

![capture d ecran 2015-05-14 a 17 51 25](https://cloud.githubusercontent.com/assets/2240469/7635638/6b046dee-fa62-11e4-9888-77594d9fc74f.png)

**Comment by martindaniel4** [comment]
@samronsin chanmé :) 

Ca valide ce qu'on pensait non du coup ? Plus d'activité là où il y a plus de chômage ?

**Comment by samronsin** [comment]
Oui plutôt! Après il faudrait vérifier qu'on a les bonnes données sur ce jeu et tâcher de séparer les coordonnées de centres qui seraient dans la même commune...

**Comment by martindaniel4** [comment]
@samronsin yes, on va récupérer l'adresse exacte des U2A de la CRF. Ca aidera. 

On va aussi avoir les données brutes de distribution par bénéficiaire de la base AIDA, on pourra avoir plus d'éléments à analyser..

**Comment by samronsin** [comment]
@martindaniel4 super!
Tiens, en passant, la carte des stocks (mêmes commentaires).

![capture d ecran 2015-05-14 a 18 07 01](https://cloud.githubusercontent.com/assets/2240469/7635907/2b854e5c-fa64-11e4-82e1-f2b476c06f56.png)

**Comment by martindaniel4** [comment]
@samronsin très cool : )

**Comment by samronsin** [comment]
@martindaniel4 en revanche difficile de dire quelque chose de clair à partir de la variable consoRate de @lefko2000 (à part que les stocks sont faibles dans quelques centres dans le 93 et le 91). 

![capture d ecran 2015-05-14 a 18 26 20](https://cloud.githubusercontent.com/assets/2240469/7636352/101ac6ee-fa67-11e4-963b-83484169c035.png)

**Comment by martindaniel4** [comment]
@samronsin @lefko2000 si elle est élevée, cela veut dire qu'on accumule plus que ce qu'on donne ? 

(je m'emmêle les pinceaux à chaque fois)

**Comment by samronsin** [comment]
yes (moi aussi).
ici, le rayon représente la valeur absolue de consoRate et la couleur le signe: rouge si négatif, vert si positif (il y a peu de vert en région parisienne).
rouge <=> distribution > stock

**Comment by martindaniel4** [comment]
@c-o @samronsin @lefko2000 @RomainWarlop j'ai ajouté le fichier d'adresses U2A ici - https://github.com/dataforgoodfr/croixrouge/blob/master/data/croixrouge/adresse%20U2A.xlsx

On ne disposait jusque là que des centres Croix Rouge généralistes.

**Comment by c-o** [comment]
j'ajoute les coordonnées long/lat à partir des adresses précises des centres U2A.
je regarde aussi pour rajouter le code geo INSEE pour pouvoir faire le lien entre AIDA et les données de INSEE pour faire le proxy

**Comment by martindaniel4** [comment]
Cool @lefko2000 a choppé les données GPS à partir des adresses.

Cool pour le proxy, partage tes idées c est vraiment là qu on peut craquer
quelque chose

**Comment by samronsin** [comment]
@martindaniel4 @c-o cool pour les adresses et coordonnées! Je regarde de plus près + demande via variables INSEE début de semaine prochaine.

**Comment by onnlinetool** [comment]
========>>>>>>>>>>>> Telecharger Crack ici

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t
