### ISSUE TITLE
Des centres de distribution ne sont pas référencés dans la liste géographique

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#21]
Liste des id_centres n'ayant pas de correspondance dans le fichier de position géo : 

['E1101', 'E8201', 'U0701', 'U1401', 'U1601', 'U2201', 'U3301',
       'U3309', 'U4401', 'U4404', 'U7101', 'U7306', 'U7801', 'U8201',
       'U8202', 'U8203', 'U8206', 'U8208', 'U8210', 'U8212', 'U8214',
       'U8812', 'U1602', 'U1604', 'U2202', 'U4402', 'U7701', 'U7703',
       'U8209', 'U8211', 'U8216', 'U0909', 'U1105', 'U1605', 'U1701',
       'U2301', 'U2302', 'U2303', 'U4405', 'U4701', 'U6001', 'U7307',
       'U7704', 'U8205', 'U8705', 'U8801', 'U2306', 'U3313', 'U3314',
       'U3316', 'U3501', 'U4706', 'U7702', 'U8215', 'U8301', 'U8302',
       'U8503', 'U0501', 'U1103', 'U2001', 'U2402', 'U2601', 'U4403',
       'U4712', 'U5501', 'U5702', 'U6002', 'U7301', 'U7706', 'U8806',
       'U0504', 'U0505', 'U1404', 'U2206', 'U2408', 'U4601', 'U4704',
       'U4707', 'U7201', 'U8401', 'U8502', 'U8701', 'U8703', 'U8706',
       'U8901', 'E8801', 'U0604', 'U0605', 'U1104', 'U1406', 'U2308',
       'U2401', 'U3001', 'U4710', 'U5002', 'U5006', 'U6902', 'U7103',
       'U7705', 'U8504', 'U0601', 'U3315', 'U4408', 'U5001', 'U5007',
       'U6102', 'U6901', 'U7803', 'U8307', 'U0101', 'U0607', 'U1005',
       'U2002', 'U2307', 'U3202', 'U3502', 'U5003', 'U5004', 'U5008',
       'U5707', 'U6701', 'U7402', 'U7804', 'U8012', 'U8013', 'U8102',
       'U8309', 'U8704', 'U8804', 'U0107', 'U0110', 'U0402', 'U0704',
       'U0708', 'U1201', 'U2304', 'U2709', 'U3503', 'U3807', 'U3813',
       'U3814', 'U4407', 'U4501', 'U5502', 'U5503', 'U5505', 'U5506',
       'U5719', 'U7901', 'U7902', 'U8403', 'U8802', 'U8807', 'U8808',
       'U8904', 'U0105', 'U1403', 'U3201', 'U3808', 'U4502', 'U5701',
       'U5703', 'U6205', 'U7104', 'U7802', 'U7805', 'U7806', 'U7903',
       'U7905', 'U7906', 'U8007', 'U8009', 'U8105', 'U8505', 'U8803',
       'U8805', 'U8809', 'U8902', 'U8905', 'U9201', 'U9202', 'U9203',
       'U0112', 'U0610', 'U0612', 'U0911', 'U1302', 'U1305', 'U1903',
       'U2407', 'U3311', 'U4703', 'U5605', 'U5606', 'U5721', 'U6203',
       'U8217', 'U8601', 'U8602', 'U8603', 'U9206', 'U0106', 'U0114',
       'U0115', 'U0606', 'U0803', 'U1004', 'U1313', 'U1902', 'U2004',
       'U2404', 'U3203', 'U4406', 'U4414', 'U4503', 'U4708', 'U4709',
       'U5602', 'U5608', 'U5704', 'U5705', 'U6501', 'U7501', 'U7807',
       'U7904', 'U8002', 'U8103', 'U8810', 'U8811', 'U8813', 'U8906',
       'U0117', 'U0705', 'U1901', 'U2405', 'U3402', 'U4413', 'U4801',
       'U5715', 'U7405', 'U7603', 'U8903', 'U9101', 'U0118', 'U0614',
       'U1304', 'U1307', 'U1312', 'U1315', 'U2501', 'U3404', 'U4602',
       'U4804', 'U5604', 'U5716', 'U6201', 'U6202', 'U7601', 'U7808',
       'U8708', 'U4412', 'U4604', 'U5202', 'U6906', 'U7001', 'U7004',
       'U7006', 'U8014', 'U9211', 'U9301', 'E7001', 'E9501', 'U1702',
       'U3902', 'U4415', 'U5711', 'U5722', 'U5902', 'U5903', 'U5904',
       'U5906', 'U5907', 'U5908', 'U5909', 'U7003', 'U8015', 'U9001',
       'U9505', 'E6201', 'U1306', 'U1308', 'U1311', 'U3601', 'U3706',
       'U3707', 'U4901', 'U5301', 'U7005', 'U7907', 'U8003', 'U8406',
       'U9208', 'U3602', 'U4802', 'U6212', 'U7908', 'U8001', 'U8011',
       'U8218', 'U6502', 'U0116', 'U0119', 'U4409', 'U7007', 'U8010',
       'E0101', 'U7712', 'U8008', 'U9504', 'U0618', 'U2710', 'U3317',
       'U6211', 'U7002', 'U7008', 'U8107', 'U4715', 'U0120', 'U3403',
       'U4417', 'U6207', 'U9103', 'U3709', 'U6208', 'U6209', 'U6210',
       'U7009', 'U8016', 'E9001', 'U3708', 'U3710', 'U7810', 'U6213',
       'U5913', 'U9002', 'U9003', 'U9102', 'U0121', 'U5901', 'U5911',
       'U1317', 'U2711', 'U9401', 'U9213', 'E5901', 'U0122', 'U0711',
       'U5915', 'U5917', 'U5905', 'U5914', 'U6204', 'U9306', 'U8101',
       'U8402', 'U9308', 'U2101', 'U4419', 'U9314', 'U3009', 'U5101',
       'U7719', 'U8106', 'U1408', 'U2801', 'U3002', 'U3008', 'U8907',
       'U3003', 'U3204', 'U6206', 'U6503', 'U7609', 'U2208', 'U5102',
       'U6504', 'U6505', 'U7503', 'U2410', 'U9506', 'U4418', 'U6910',
       'U7714', 'U7910', 'U9105', 'U9508', 'U2901', 'U3714', 'U6904',
       'U7612', 'U8404', 'U8409', 'U9302', 'U9316', 'U9403', 'U9404',
       'U1318', 'U1319', 'U1908', 'U3318', 'U3409', 'U3716', 'U6905',
       'U6911', 'U7610', 'U9503', 'U0123', 'U0302', 'U0617', 'U2210',
       'U3006', 'U3101', 'U3102', 'U3408', 'U3603', 'U7613', 'U7711',
       'U9106', 'U9315', 'U9318', 'WITBE', 'U0801', 'U3303', 'U7720',
       'U0111', 'U0301', 'U4902', 'U5405', 'U5916', 'U5920', 'U6403',
       'U6404', 'U6405', 'U6603', 'U6907', 'U9509', 'U9510']

**Comment by samronsin** [comment]
comment a-t-on obtenu les données de position? CRF directement?

**Comment by martindaniel4** [comment]
oui, elles sont dispos là - https://github.com/dataforgoodfr/croixrouge/blob/master/data/croixrouge/position_centres_2015_CRF.xlsx

**Comment by samronsin** [comment]
donc c'est eux qui ne sont pas cohérents dans leurs jeux de données?

**Comment by martindaniel4** [comment]
non, je pense que la raison est que AIDA (le logiciel depuis lequel on a les données) n'est pas utilisé depuis le début ou pas par tout le monde. Du coup on a des trous.

**Comment by martindaniel4** [comment]
@lefko2000 @c-o @samronsin - c'est quoi la conclusion finalement là dessus ? On s'est planté de fichier c'est ça ?
