### ISSUE TITLE
Décrire les tables brutes dans BQ

### ISSUE THREAD

**Issue by RomainWarlop** [dataforgoodfr/croixrouge#27]
Remplir les champs "describe this field" dans l'onglet schema des tables sur https://bigquery.cloud.google.com/welcome/croix-rouge-92715

**Comment by martindaniel4** [comment]
@RomainWarlop ok je la prends celle là

**Comment by martindaniel4** [comment]
@RomainWarlop en fait je me demande si on a besoin de toute la table.. 

On pourrait créer une nouvelle table avec les colonnes qui nous intéressent, en gros : 

`centre,item,date_peremption,date_stockage,quantité,poids,origine`

t'en penses quoi ?

**Comment by RomainWarlop** [comment]
@martindaniel4 Yes on peut faire ça c'est pas con. Après je sais pas ce qu'il y a dans les autres colonnes donc j'ai un peu de mal à imaginer ce qui peut être intéressant à garder. 
Y'a plusieurs champs de date, tu connais leur différence ? Y'a une colonne qui indique la provenance ? Et la sur famille des produits ou il faut matcher avec les bases MySQL ?

**Comment by martindaniel4** [comment]
@RomainWarlop famille de produits, on a une table de correspondance qui s'appelle `ITMMASTER` mais qui est vide pour l'instant, je vais redemander l'export. 

Peut être que @odtvince peut aider pour matcher les produits en attendant avec OFF ?

**Comment by martindaniel4** [comment]
@RomainWarlop, pour les champs date, voilà ce que j'ai : 
- DLUDAT_0 est la date limite d’utilisation que nous retrouvons sur les aliments
- NEWLTIDAT_0 est la date de recontrôle
- CREMVTDAT_0 est la date de création

**Comment by RomainWarlop** [comment]
@martindaniel4 cool merci ! y'a UPDDAT_0 comme champs de date qui est un chelou. ça peut être la date de création du centre ?

**Comment by martindaniel4** [comment]
cf - https://github.com/dataforgoodfr/croixrouge/blob/master/data/croixrouge/AIDA%20brut/structure%20ITMMASTER%20SINVOICE%20SINVOICEV.xlsx
