### ISSUE TITLE
Supprimer les outliers des Tables STO_FOUR_ORI et ART_DIS_SURFAMILLE pour QTE_NETTE et POIDS_NET

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/croixrouge#3]
Il semble que les tables `STO_FOUR_ODI` et `ART_DIS_SURFAMILLE` présentent des anomalies de saisi pour les QTE_NETTE et les POIDS_NET e.g : 

| LB_U2A | CD_SUR_FAM_ART | POIDS_NET | QTE_NETTE |
| --- | --- | --- | --- |
| 201111 | Epicerie sociale de St Maixent-l'École | FEC | 2.416330e+14 |
| 201201 | Centre distribution Pont de Vaux | FEC | 1.798820e+14 |
| 201202 | Centre distribution de Lyon 6 | PGS | 5.490530e+13 |
| 201104 | Centre de distribution de Limoux | FL | 9.841420e+13 |

Ces anomalies concernent les produits alimentaires et ont l'air d'avoir lieu entre 2011 et 2012 : 

![evolution_poids_qte](https://cloud.githubusercontent.com/assets/695006/7005798/c36bfc7c-dc7b-11e4-8ead-52b13420b8bc.png)

Les deux tables sont concernées, mais pas au même date / centre de distribution. 

Idées pour corriger ça : 
- Fixer l'amplitude de 2011 - 2012 au double de l'amplitude de 2013 - 2014

**Comment by martindaniel4** [comment]
Il s'agit de codes barres qui ont été interprétés comme des poids / quantité. 

Il faudrait trouver une méthode pour supprimer ces outliers.

**Comment by c-o** [comment]
je pense qu'une règle du type "si 13 chiffres, c'est un code barre" ça devrait faire l'affaire :)

**Comment by martindaniel4** [comment]
Bon y a clairement un gap d'ordre de grandeur dans les données remontées : 

![capture d ecran 2015-04-24 a 09 56 15](https://cloud.githubusercontent.com/assets/695006/7314812/3fdf3fb8-ea68-11e4-916a-abab226a98d6.png)

@lefko2000 tu peux partager ta méthodo please ?

**Comment by selimrbd** [comment]
Probleme resolu avec le dernier commit n#08f3200a80
