### ISSUE TITLE
liste géolocalisée des centres de distribution hors croix rouge

### ISSUE THREAD

**Issue by c-o** [dataforgoodfr/croixrouge#6]
La croix rouge s'entend localement avec les autres associations sur l'implantation de ses centres. Une zone sans centre croix rouge peut parfois s'expliquer par la présence connue d'une autre association.
Il nous faut donc trouver l'information d'implantation des centres de : 
- Restos du Coeur
- Banque Alimentaire
- Secours Populaire Français
  voire d'autres associations plus locales

pistes pour avoir ces données: 
- la croix rouge eux même ?
- contacter directement les ONG ?
- recensement existant ?
- Etalab ?

**Comment by martindaniel4** [comment]
Pour ceux qui sont sur Python et qui veulent faire des cartes, cette petite librairie `folium` - https://pypi.python.org/pypi/folium vous permet de faire des cartes interactives en utilisant leaflet.js

**Comment by martindaniel4** [comment]
@c-o on doit pouvoir récupérer les emplacements exacts en utilisant cette carte - http://www.croix-rouge.fr/Pres-de-chez-vous

**Comment by c-o** [comment]
t'es sur qu' c'est pas que les centres de la croix rouge? du coup on a une visu du maillage actuel, c'est super dense !
dans tous les cas la base derrière est à récupérer ! => label pourcroixrouge, on demandera au prochain batch de demande d'info (pas les bombarder de demandes)

**Comment by martindaniel4** [comment]
@c-o ok j'ai ajouté les centres de distribution localisés de la croix rouge ici - https://github.com/dataforgoodfr/croixrouge/blob/master/data/croixrouge/structures_2015_CRF.xlsx
