### ISSUE TITLE
Récupérer les données INSEE (ou plus) socio/demo par ville / canton / departement

### ISSUE THREAD

**Issue by c-o** [dataforgoodfr/croixrouge#7]
Nous souhaitons correler la demande actuelle des centres de distributions avec un proxy socio/demo. Nous devons pour cela récupérer toutes les statistiues susceptibles d'affiner un modèle:
- distribution des revenus par foyer
- taux de chomage 
- densité de population
- ...
  idéalement nous pourrions réaliser l'étude au niveau de la ville, ou le canton, et par défaut, le département.

**Comment by martindaniel4** [comment]
Pas mal de choses à récupérer ici - http://snips.net/blog/posts/2014/02-18-predicting-abstention-rate-from-open-data.html

**Comment by martindaniel4** [comment]
@c-o ok j'ai pushé des données ici - https://github.com/dataforgoodfr/croixrouge/tree/master/data/INSEE

En train de les documenter là - https://github.com/dataforgoodfr/croixrouge/wiki/Description-des-tables-INSEE

**Comment by samronsin** [comment]
@martindaniel4 Les données du chômage pourraient directement modéliser la demande en première approximation, non? J'ai vu qu'elles étaient dispo en .xls... Par ailleurs celles que tu as uploadées sont dans quel format? Je ne peux pas les dézipper!

**Comment by martindaniel4** [comment]
@samronsin t'as essayé ça ? https://github.com/vallettea/politics-open-data/blob/master/election_cleaner.py#L38

**Comment by martindaniel4** [comment]
@samronsin en fait je les dézippe et je les lis avec [pandas.read_excel](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.io.excel.read_excel.html)
