### ISSUE TITLE
conseil sur un package adapté au travail de données géolocalisées francaise

### ISSUE THREAD

**Issue by c-o** [dataforgoodfr/croixrouge#8]
Nous allons travailler sur des données géolocalisées, avec des limites de villes, cantons, département, région.
Existe-t-il des packages intégrant ces différentes notions avec leur définissions long/lat pour le territoire français?
language R et / ou Pyhton de préférence

**Comment by RomainWarlop** [comment]
En R il y a la library mapproj :

library(mapproj)
library(ggplot2)
geo <- map_data('france')
geo <- subset(geo, long>-50 & long < 50 & lat > 40) # Trim off islands
ggplot(geo, aes(x=long, y=lat, group=group)) +
  geom_polygon(colour="black") +
  coord_map("polyconic")

Dans geo il n'y a pas les villes, mais il est facile de trouver un dataset avec la liste des villes, leur long/lat et faire le join
(cf <a href="https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCkQFjAB&url=http%3A%2F%2Fdeca.cuc.edu.cn%2FCommunity%2Fmedia%2Fp%2F23508%2Fdownload.aspx&ei=8JErVfjHCYLpasnBgOAK&usg=AFQjCNHJNZvnRcHXqfmXzNGuwmVRsEZD1A&bvm=bv.90491159,d.bGQ&cad=rja"> R Graphics Cookbook</a> pour plus de détails)

**Comment by martindaniel4** [comment]
@RomainWarlop, @c-o quand à la liste des villes y a pas mal de trucs là - http://sql.sh/736-base-donnees-villes-francaises

**Comment by samronsin** [comment]
Shapely peut-être en python? Avec des données à trouver pour les frontières...
https://pypi.python.org/pypi/Shapely

**Comment by martindaniel4** [comment]
Y a ça aussi qui est cool - https://github.com/python-visualization/folium

**Comment by martindaniel4** [comment]
@samronsin @c-o @RomainWarlop complètement ouf [Folium](https://github.com/python-visualization/folium). Je viens de faire en 5 lignes, en m'inspirant [de ce tutoriel](http://nbviewer.ipython.org/gist/bburky/7763555/folium-ipython.ipynb), cette carte (Stamen-style avec Leaflet.js) de la répartition des centres croix rouge en France :

![capture d ecran 2015-04-14 a 23 10 08](https://cloud.githubusercontent.com/assets/695006/7147556/0d397074-e2fc-11e4-8889-632133c3deee.png)

Le résultat est interactif, je l'ai pushé sur le serveur de dataforgood là - http://www.dataforgood.fr/crf.html

Si vous avez iPython vous pouvez récupérer mon notebook là - https://github.com/dataforgoodfr/croixrouge/tree/master/exploration%20

Sinon mon code fait quelque chose comme : 

``` python

# import libs
import pandas as pd
import folium
from IPython.display import HTML

#load centres CRF
centres = pd.read_excel("../data/croixrouge/structures_2015_CRF.xlsx")

#To make inline maps in notebook
def inline_map(map):
    map._build_map()
    return HTML('<iframe srcdoc="{srcdoc}" style="width: 100%; height: 510px; border: none"></iframe>'.format(srcdoc=map.HTML.replace('"', '&quot;')))

# Draw map
map = folium.Map(location=[48.8655909,2.378983], zoom_start=6,tiles="Stamen Toner")

#Draw circles
for x in centres.values:
    location = []
    location.append(x[4])
    location.append(x[5])
    map.circle_marker(location,radius=2,fill_color='red',popup=x[1])

#Display map
inline_map(map)
```

A première vue, très forte concentration en région parisienne. Pourrait être intéressant de mapper ça avec la population. 

Exciting !

**Comment by RomainWarlop** [comment]
@martindaniel4 BOUM :+1:

**Comment by martindaniel4** [comment]
@RomainWarlop je vois pas si tu captes, mais il y a aussi un attribut `popup`dans la méthode `map`. Ca te permet d'y mettre du contenu qui sera affiché sous la forme d'une infobulle dans ta carte. C'est vraiment cool pour explorer un set géographique.

**Comment by samronsin** [comment]
Cool!

**Comment by c-o** [comment]
un peu tard, mais :+1: merci @martindaniel4 de nous faire découvrir folium
